application:
  recover:
    enabled: true
    level: WARN
    no-recover-for:
      - java.lang.IllegalArgumentException
      - java.lang.IllegalStateException
  logging:
    enabled: true
    level: WARN
    print-args: true
server:
  port: 8082
spring:
  application:
    name: timesheet-rest
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
